name: dev to main sync


#Run workflow on successful merge to dev
on:
  push:
    branches:
      - dev


jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: tibdex/github-app-token@586e1a624db6a5a4ac2c53daeeded60c5e3d50fe
        id: generate-token
        with:
          app_id: ${{ secrets.PRBOT_APP_ID }}
          private_key: ${{ secrets.PRBOT_APP_PRIVATE_KEY }}


      - name: Create pull request to merge into main
        uses: actions/create-pull-request@v4
        with:
          title: Merge ${{ github.ref }} into main
          head: ${{ github.ref }}
          base: main
          body: Merge ${{ github.ref }} into main. Please approve if you agree to sync dev site to main, otherwise reject.
          token: ${{ steps.generate-token.outputs.token }}