name: dev to main sync


#Run workflow on successful merge to dev
on:
  push:
    branches:
      - dev


jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: tibdex/github-app-token@586e1a624db6a5a4ac2c53daeeded60c5e3d50fe
        id: generate-token
        with:
          app_id: ${{ secrets.PRBOT_APP_ID }}
          private_key: ${{ secrets.PRBOT_APP_PRIVATE_KEY }}

      #Sync dev branch to the main branch to keep it updated
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@ea58ab6e406fd3ad016a064b31270bbb41127f41
        with:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          FROM_BRANCH: "dev"
          TO_BRANCH: "main"
          REVIEWERS: '["bradjohnl", "ipopescu", "ACStoneCL", "bdkpathi", "GloreenS"]'
          CONTENT_COMPARISON: true
          PULL_REQUEST_BODY: "This PR is created by the PR Bot to sync the dev branch to the main branch. Please check the content changes also on the staging site if you want. You can feel free to ignore this or approve + merge it. If you merge, the prod deployment will start automatically. If you ignore it, it will get renewed the next time a new feature gets merged to the dev branch."
          PULL_REQUEST_TITLE: "Sync dev to main"

      #Display the pull request URL:
      - name: Display the pull request URL
        run: | 
          echo "The pull request URL is: ${{ steps.pull.outputs.PULL_REQUEST_URL }}"
