name: dev to feature sync


#Run workflow on successful merge to dev
on:
  push:
    branches:
      - dev


jobs:
  setup-fb-sync:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-branch-matrix.outputs.branch_list }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Ruby
        run: |
          sudo apt-get update && sudo apt-get install -y ruby-full ruby-bundler build-essential

      - name: Get all the branches in the repository that begin with feat-* and save the results a single-line JSON array
        run: |
          echo "BRANCH_ARRAY=[$( git branch -r | grep "feat-" | sed 's/[[:space:]]*//' | sed 's/.*\///' | ruby -ryaml -e 'puts ARGF.read.lines.map { |l| l.chomp.inspect }.join(", ")' | tail -n 1)]" >> $GITHUB_ENV
        
      - name: Populate the branch matrix
        id: setup-branch-matrix
        run: |
          echo "::set-output name=branch_list::$BRANCH_ARRAY"
        
  create-pull-request-fb:
    if: ${{ needs.setup-fb-sync.outputs.matrix != '[]' }} 
    needs: [ setup-fb-sync ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch_list: ${{ fromJson(needs.setup-fb-sync.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v3

      - uses: tibdex/github-app-token@586e1a624db6a5a4ac2c53daeeded60c5e3d50fe
        id: generate-token
        with:
          app_id: ${{ secrets.PRBOT_APP_ID }}
          private_key: ${{ secrets.PRBOT_APP_PRIVATE_KEY }}

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@ea58ab6e406fd3ad016a064b31270bbb41127f41
        with:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          FROM_BRANCH: "dev"
          TO_BRANCH: "${{ matrix.branch_list }}"
          REVIEWERS: '["bradjohnl", "ipopescu", "ACStoneCL", "bdkpathi", "GloreenS"]'
          CONTENT_COMPARISON: true
          PULL_REQUEST_BODY: "This PR is created by the PR Bot to sync the dev branch to the ${{ matrix.branch_list }} branch. To avoid conflicts, the feature branches should be kept in sync with the dev branch"
          PULL_REQUEST_TITLE: "Sync dev to ${{ matrix.branch_list }}"

      #Display the pull request URL:
      - name: Display the pull request URL
        run: | 
          echo "The pull request URL is: ${{ steps.pull.outputs.PULL_REQUEST_URL }}"
