name: Docusaurus CICD

on:
  push:
    branches: "*"
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  backup:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - uses: actions/upload-artifact@v2
        with:
          name: gh-pages-backup
          path: .
        

  build:
    runs-on: ubuntu-latest

    env:
      selected_node_version: 14

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.selected_node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.selected_node_version }}
          cache: yarn
      
      - name: Template credentials
        if: github.ref == 'refs/heads/main'
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: .github/templates/.env.production.j2
          output_file: .env.production
        env:
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          CROWDIN_PERSONAL_ACCESS_TOKEN: ${{ secrets.CROWDIN_PERSONAL_ACCESS_TOKEN }}
          GOOGLE_ANALYTICS_TRACKING_ID: ${{ secrets.GOOGLE_ANALYTICS_TRACKING_ID }}
          GOOGLE_ANALYTICS_ANONYMIZE_IP: ${{ secrets.GOOGLE_ANALYTICS_ANONYMIZE_IP }}
          GOOGLE_TAG_TRACKING_ID: ${{ secrets.GOOGLE_TAG_TRACKING_ID }}
          
      - name: Yarn install
        run: |
          yarn install

      - name: Run code analysis
        run: |
          yarn format

      - name: Build app
        run: |
          yarn build --out-dir ./docs

      - uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/main'
        with:
          name: gh-pages-depl-payload
          path: ./docs

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: [build, backup]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@master
      with:
        name: gh-pages-depl-payload
        path: ./docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

  test-prod:
    needs: deploy-prod
    runs-on: ubuntu-latest

    env:
      prod_pages_url: ${{ secrets.PROD_PAGES_URL }}

    steps:
      - name: Test home page
        run: |
          echo "Testing if homepage responds correctly"
          curl --fail $prod_pages_url
      - name: Test a random page
        run: |
          echo "Testing if a page responds correctly"
          curl --fail $prod_pages_url/operators/create
      - name: Test another random page
        run: |
          echo "Testing if a page responds correctly"
          curl --fail $prod_pages_url/design/serialization-standard

  rollback-if-tests-fail:
    if: ${{ always() && (needs.test-prod.result=='failure') }}
    needs: test-prod
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@master
      with:
        name: gh-pages-backup
        path: ./docs

    - name: Deploy the previous version to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

      
